// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.


package models

import (
	"time"
)

const TableNameDatasourceElkcollectresult = "datasource_elkcollectresult"

// DatasourceElkcollectresult mapped from table <datasource_elkcollectresult>
type DatasourceElkcollectresult struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt         time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	StartAt           time.Time `gorm:"column:start_at" json:"start_at"`
	FinishAt          time.Time `gorm:"column:finish_at" json:"finish_at"`
	Success           bool      `gorm:"column:success;not null" json:"success"`
	Status            string    `gorm:"column:status;not null" json:"status"`
	Detail            string    `gorm:"column:detail;not null;type:jsonb" json:"detail"`
	Jid               string    `gorm:"column:jid;not null" json:"jid"`
	QueryFromDatetime time.Time `gorm:"column:query_from_datetime" json:"query_from_datetime"`
	QueryToDatetime   time.Time `gorm:"column:query_to_datetime" json:"query_to_datetime"`

	CollectorID int64                        `gorm:"column:collector_id;not null" json:"collector_id"`
	Collector   DatasourceElkcollectorconfig `gorm:"foreignKey:CollectorID"`
}

// TableName DatasourceElkcollectresult's table name
func (*DatasourceElkcollectresult) TableName() string {
	return TableNameDatasourceElkcollectresult
}
