// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDatasourceProxyconfig = "datasource_proxyconfig"

// DatasourceProxyconfig mapped from table <datasource_proxyconfig>
type DatasourceProxyconfig struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Address   string    `gorm:"column:address;not null" json:"address"`
	Port      int32     `gorm:"column:port" json:"port"`
	Username  string    `gorm:"column:username" json:"username"`
	Password  string    `gorm:"column:password" json:"password"`
	Options   string    `gorm:"column:options;not null" json:"options"`
}

// TableName DatasourceProxyconfig's table name
func (*DatasourceProxyconfig) TableName() string {
	return TableNameDatasourceProxyconfig
}

func (pc *DatasourceProxyconfig) BuildProxyUrl() string {
	proxyUrl := ""
	if pc.Username != "" && pc.Password != "" {
		proxyUrl = pc.Username + ":" + pc.Password + "@"
	}
	if pc.Port != 0 {
		proxyUrl += pc.Address + ":" + string(pc.Port)
	} else {
		proxyUrl += pc.Address
	}
	return proxyUrl
}