// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDatasourceElkquery = "datasource_elkquery"

// DatasourceElkquery mapped from table <datasource_elkquery>
type DatasourceElkquery struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Code        string    `gorm:"column:code;not null" json:"code"`
	Description string    `gorm:"column:description;not null" json:"description"`
	Index       string    `gorm:"column:index;not null" json:"index"`
	Query       string    `gorm:"column:query;not null" json:"query"`
}

// TableName DatasourceElkquery's table name
func (*DatasourceElkquery) TableName() string {
	return TableNameDatasourceElkquery
}
