// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDatasourceElkcollectorconfigElkQuery = "datasource_elkcollectorconfig_elk_queries"

// DatasourceElkcollectorconfigElkQuery mapped from table <datasource_elkcollectorconfig_elk_queries>
type DatasourceElkcollectorconfigElkQuery struct {
	ID                   int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ElkcollectorconfigID int64 `gorm:"column:elkcollectorconfig_id;not null" json:"elkcollectorconfig_id"`
	ElkqueryID           int64 `gorm:"column:elkquery_id;not null" json:"elkquery_id"`
}

// TableName DatasourceElkcollectorconfigElkQuery's table name
func (*DatasourceElkcollectorconfigElkQuery) TableName() string {
	return TableNameDatasourceElkcollectorconfigElkQuery
}
