// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDatasourceElkcollectorconfig = "datasource_elkcollectorconfig"

// DatasourceElkcollectorconfig mapped from table <datasource_elkcollectorconfig>
type DatasourceElkcollectorconfig struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Code          string    `gorm:"column:code;not null" json:"code"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	IntervalValue int32     `gorm:"column:interval_value;not null" json:"interval_value"`
	IntervalUnit  string    `gorm:"column:interval_unit;not null" json:"interval_unit"`
	LastRunAt     time.Time `gorm:"column:last_run_at" json:"last_run_at"`
	Active        bool      `gorm:"column:active;not null" json:"active"`
	ElkConfigID   int64     `gorm:"column:elk_config_id;not null" json:"elk_config_id"`

	ElkConfig     DatasourceElkconfig     `gorm:"foreignKey:ElkConfigID"`
    ElkQueries    []DatasourceElkquery    `gorm:"many2many:datasource_elkcollectorconfig_elk_queries;joinForeignKey:ElkcollectorconfigID;joinReferences:ElkqueryID"`
    LogFilters    []DatasourceLogfilter   `gorm:"many2many:datasource_elkcollectorconfig_log_filters;joinForeignKey:ElkcollectorconfigID;joinReferences:LogfilterID"`
    Results       []DatasourceElkcollectresult `gorm:"foreignKey:CollectorID"`
}

// TableName DatasourceElkcollectorconfig's table name
func (*DatasourceElkcollectorconfig) TableName() string {
	return TableNameDatasourceElkcollectorconfig
}

func (cc *DatasourceElkcollectorconfig) GetInterval() int32 {
	switch cc.IntervalUnit {
	case "second":
		return cc.IntervalValue
	case "minute":
		return cc.IntervalValue * 60
	case "hour":
		return cc.IntervalValue * 3600
	case "day":
		return cc.IntervalValue * 86400
	default:
		return cc.IntervalValue
	}
}
