// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDatasourceElkconfig = "datasource_elkconfig"

// DatasourceElkconfig mapped from table <datasource_elkconfig>
type DatasourceElkconfig struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Code        string    `gorm:"column:code;not null" json:"code"`
	Host        string    `gorm:"column:host;not null" json:"host"`
	Port        int32     `gorm:"column:port;not null" json:"port"`
	Username    string    `gorm:"column:username" json:"username"`
	Password    string    `gorm:"column:password" json:"password"`
	Options     string    `gorm:"column:options;not null" json:"options"`
	ProxyEnable bool      `gorm:"column:proxy_enable;not null" json:"proxy_enable"`
	ProxyID     int64     `gorm:"column:proxy_id" json:"proxy_id"`

	Proxy     DatasourceProxyconfig     `gorm:"foreignKey:ProxyID"`
}

// TableName DatasourceElkconfig's table name
func (*DatasourceElkconfig) TableName() string {
	return TableNameDatasourceElkconfig
}
