// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameDatasourceLogfilter = "datasource_logfilter"

// DatasourceLogfilter mapped from table <datasource_logfilter>
type DatasourceLogfilter struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Code        string    `gorm:"column:code;not null" json:"code"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description string    `gorm:"column:description" json:"description"`
	FilterType  string    `gorm:"column:filter_type;not null" json:"filter_type"`
	Priority    int32     `gorm:"column:priority;not null" json:"priority"`
	CompareType string    `gorm:"column:compare_type;not null" json:"compare_type"`
	Active      bool      `gorm:"column:active;not null" json:"active"`
}

// TableName DatasourceLogfilter's table name
func (*DatasourceLogfilter) TableName() string {
	return TableNameDatasourceLogfilter
}
