// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameDatasourceElkcollectorconfigLogFilter = "datasource_elkcollectorconfig_log_filters"

// DatasourceElkcollectorconfigLogFilter mapped from table <datasource_elkcollectorconfig_log_filters>
type DatasourceElkcollectorconfigLogFilter struct {
	ID                   int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ElkcollectorconfigID int64 `gorm:"column:elkcollectorconfig_id;not null" json:"elkcollectorconfig_id"`
	LogfilterID          int64 `gorm:"column:logfilter_id;not null" json:"logfilter_id"`
}

// TableName DatasourceElkcollectorconfigLogFilter's table name
func (*DatasourceElkcollectorconfigLogFilter) TableName() string {
	return TableNameDatasourceElkcollectorconfigLogFilter
}
