// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameReportElkgrouplog = "report_elkgrouplog"

// ReportElkgrouplog mapped from table <report_elkgrouplog>
type ReportElkgrouplog struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CollectorCode string    `gorm:"column:collector_code;not null" json:"collector_code"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Key           string    `gorm:"column:key;not null" json:"key"`
}

// TableName ReportElkgrouplog's table name
func (*ReportElkgrouplog) TableName() string {
	return TableNameReportElkgrouplog
}
