// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
	"gorm.io/datatypes"
)

const TableNameReportElkcollectedlog = "report_elkcollectedlog"

// ReportElkcollectedlog mapped from table <report_elkcollectedlog>
type ReportElkcollectedlog struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt     time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	CollectorCode string    `gorm:"column:collector_code;not null" json:"collector_code"`
	LogID         string    `gorm:"column:log_id;not null" json:"log_id"`
	LogType       string    `gorm:"column:log_type;not null" json:"log_type"`
	LogRaw        datatypes.JSON    `gorm:"column:log_raw;not null" json:"log_raw"`
	LogTimestamp  float64   `gorm:"column:log_timestamp;not null" json:"log_timestamp"`
}

// TableName ReportElkcollectedlog's table name
func (*ReportElkcollectedlog) TableName() string {
	return TableNameReportElkcollectedlog
}
