// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameReportElkgrouplogLog = "report_elkgrouplog_logs"

// ReportElkgrouplogLog mapped from table <report_elkgrouplog_logs>
type ReportElkgrouplogLog struct {
	ID                int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ElkgrouplogID     int64 `gorm:"column:elkgrouplog_id;not null" json:"elkgrouplog_id"`
	ElkcollectedlogID int64 `gorm:"column:elkcollectedlog_id;not null" json:"elkcollectedlog_id"`
}

// TableName ReportElkgrouplogLog's table name
func (*ReportElkgrouplogLog) TableName() string {
	return TableNameReportElkgrouplogLog
}
