# Generated by Django 5.2 on 2025-04-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElkCollectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Code of the Collector', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Host of the ELK server', max_length=255)),
                ('interval_value', models.IntegerField(default=30, help_text='Interval value for the collector config')),
                ('interval_unit', models.CharField(choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours')], default='seconds', help_text='Interval unit for the collector config', max_length=10)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last time the collector config was run', null=True)),
                ('active', models.BooleanField(default=True, help_text='Is this collector config active?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Code of the ELK server', max_length=255, unique=True)),
                ('host', models.CharField(help_text='Host of the ELK server', max_length=255)),
                ('port', models.IntegerField(help_text='Port of the ELK server')),
                ('username', models.CharField(blank=True, help_text='Username for ELK server', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text='Password for ELK server', max_length=255, null=True)),
                ('options', models.JSONField(default=dict, help_text='Additional options for ELK server')),
                ('proxy_enable', models.BooleanField(default=False, help_text='Is proxy enabled?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElkQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the query', max_length=255)),
                ('code', models.CharField(help_text='Code of the query', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of the query')),
                ('index', models.CharField(help_text='Index to be queried', max_length=255)),
                ('query', models.JSONField(default=dict, help_text='Query to be executed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text='Host of the ELK server', max_length=255)),
                ('port', models.IntegerField(blank=True, help_text='Port of the ELK server', null=True)),
                ('username', models.CharField(blank=True, help_text='Username for ELK server', max_length=255, null=True)),
                ('password', models.CharField(blank=True, help_text='Password for ELK server', max_length=255, null=True)),
                ('options', models.JSONField(default=dict, help_text='Additional options for ELK server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElkCollectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(blank=True, help_text='Start time of the collection', null=True)),
                ('finish_at', models.DateTimeField(blank=True, help_text='Finish time of the collection', null=True)),
                ('success', models.BooleanField(default=False, help_text='Was the collection successful?')),
                ('status', models.CharField(help_text='Status of the collection result', max_length=255)),
                ('detail', models.JSONField(default=dict, help_text='Details of the collection result')),
                ('collector', models.ForeignKey(help_text='The collector config this result belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='collect_results', to='datasource.elkcollectorconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='elkcollectorconfig',
            name='elk_config',
            field=models.ForeignKey(help_text='The ELK client config this config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='collector_configs', to='datasource.elkconfig'),
        ),
        migrations.AddField(
            model_name='elkcollectorconfig',
            name='elk_queries',
            field=models.ManyToManyField(help_text='The ELK queries this config belongs to', related_name='collector_configs', to='datasource.elkquery'),
        ),
        migrations.AddField(
            model_name='elkconfig',
            name='proxy',
            field=models.ForeignKey(blank=True, help_text='Proxy config for ELK server', null=True, on_delete=django.db.models.deletion.CASCADE, to='datasource.proxyconfig'),
        ),
    ]
