# Generated by Django 5.2 on 2025-04-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('filter_type', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('compare_type', models.CharField(choices=[('equal', 'Equal'), ('startswith', 'Startswith'), ('endswith', 'Endswith'), ('include', 'Include'), ('exclude', 'Exclude'), ('search', 'Search')], default='seconds', help_text='Interval unit for the collector config', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='elkcollectorconfig',
            name='log_filters',
            field=models.ManyToManyField(help_text='The log filters this config belongs to', related_name='collector_configs', to='datasource.logfilter'),
        ),
    ]
