# Generated by Django 5.2 on 2025-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_logfilter_elkcollectorconfig_log_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elkcollectorconfig',
            name='elk_queries',
            field=models.ManyToManyField(blank=True, help_text='The ELK queries this config belongs to', null=True, related_name='collector_configs', to='datasource.elkquery'),
        ),
        migrations.AlterField(
            model_name='elkcollectorconfig',
            name='log_filters',
            field=models.ManyToManyField(blank=True, help_text='The log filters this config belongs to', null=True, related_name='collector_configs', to='datasource.logfilter'),
        ),
    ]
