# Generated by Django 5.2 on 2025-04-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_alter_elkcollectorconfig_elk_queries_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elkcollectorconfig',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='elkcollectresult',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='elkconfig',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='elkquery',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddIndex(
            model_name='elkcollectorconfig',
            index=models.Index(fields=['code'], name='datasource__code_78f6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectorconfig',
            index=models.Index(fields=['active'], name='datasource__active_b9354c_idx'),
        ),
        migrations.AddIndex(
            model_name='elkconfig',
            index=models.Index(fields=['code'], name='datasource__code_488d44_idx'),
        ),
        migrations.AddIndex(
            model_name='elkquery',
            index=models.Index(fields=['code'], name='datasource__code_2b44d7_idx'),
        ),
    ]
