# Generated by Django 5.2 on 2025-04-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_alter_elkcollectorconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elkcollectresult',
            name='jid',
            field=models.CharField(blank=True, help_text='Job ID of the collection job', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='elkcollectresult',
            name='query_from_datetime',
            field=models.DateTimeField(blank=True, help_text='Start time of the query', null=True),
        ),
        migrations.AddField(
            model_name='elkcollectresult',
            name='query_to_datetime',
            field=models.DateTimeField(blank=True, help_text='End time of the query', null=True),
        ),
        migrations.AddIndex(
            model_name='elkcollectresult',
            index=models.Index(fields=['jid'], name='datasource__jid_3f96d3_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectresult',
            index=models.Index(fields=['success'], name='datasource__success_44bc4d_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectresult',
            index=models.Index(fields=['status'], name='datasource__status_9741f2_idx'),
        ),
    ]
