# Generated by Django 5.2 on 2025-04-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElkCollectedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector_code', models.CharField(max_length=100, verbose_name='Collector Code')),
                ('log_id', models.CharField(max_length=100, unique=True)),
                ('log_type', models.CharField(max_length=50, verbose_name='Log Type')),
                ('log_raw', models.JSONField(default=dict, verbose_name='Log Raw')),
                ('log_timestamp', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElkGroupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector_code', models.CharField(max_length=100, verbose_name='Collector Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key')),
                ('logs', models.ManyToManyField(related_name='elk_group_logs', to='report.elkcollectedlog', verbose_name='Logs')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
