# Generated by Django 5.2 on 2025-04-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elkcollectedlog',
            options={'ordering': ['-log_timestamp']},
        ),
        migrations.AddField(
            model_name='elkcollectedlog',
            name='value',
            field=models.TextField(default='', max_length=10240, verbose_name='Value'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['collector_code'], name='report_elkc_collect_9a9aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['log_type'], name='report_elkc_log_typ_4c9b98_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['log_id'], name='report_elkc_log_id_a01e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['log_timestamp'], name='report_elkc_log_tim_20a775_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['log_type', 'log_id'], name='report_elkc_log_typ_81b7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['log_type', 'log_id', 'log_timestamp'], name='report_elkc_log_typ_ded26e_idx'),
        ),
        migrations.AddIndex(
            model_name='elkcollectedlog',
            index=models.Index(fields=['collector_code', 'log_type', 'log_id'], name='report_elkc_collect_74e179_idx'),
        ),
    ]
